# Generated by Django 4.1.6 on 2023-05-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matriculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direc', models.IntegerField()),
                ('municipio', models.CharField(max_length=255)),
                ('mat1Serie', models.IntegerField()),
                ('mat2Serie', models.IntegerField()),
                ('mat3Serie', models.IntegerField()),
            ],
        ),
    ]
