# Generated by Django 4.1.6 on 2023-05-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Painel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direc', models.IntegerField()),
                ('nomeMunicipio', models.CharField(max_length=255)),
                ('codEscola', models.IntegerField()),
                ('nomeEscola', models.CharField(max_length=255)),
                ('ofertaFund', models.IntegerField()),
                ('ofertaEJA', models.IntegerField()),
                ('mat1Serie', models.IntegerField()),
                ('mat2Serie', models.IntegerField()),
                ('mat3Serie', models.IntegerField()),
                ('matNoturno', models.IntegerField()),
                ('matDiurnoParcial', models.IntegerField()),
                ('matDiurnoIntegral', models.IntegerField()),
                ('matRegular', models.IntegerField()),
                ('matProfissional', models.IntegerField()),
                ('taxApr1Serie', models.FloatField()),
                ('taxApr2Serie', models.FloatField()),
                ('taxApr3Serie', models.FloatField()),
                ('taxRet1Serie', models.FloatField()),
                ('taxRet2Serie', models.FloatField()),
                ('taxRet3Serie', models.FloatField()),
                ('taxEva1Serie', models.FloatField()),
                ('taxEva2Serie', models.FloatField()),
                ('taxEva3Serie', models.FloatField()),
                ('taxAprMedia', models.FloatField()),
                ('taxRepMedia', models.FloatField()),
                ('taxEvaMedia', models.FloatField()),
                ('idebEscola', models.FloatField()),
                ('idebRN', models.FloatField()),
                ('simaisPor', models.FloatField()),
                ('simaisMat', models.FloatField()),
                ('metSimaisPor', models.FloatField()),
                ('metSimaisMat', models.FloatField()),
                ('metIdebEscola', models.FloatField()),
                ('metIdebRN', models.FloatField()),
            ],
        ),
    ]
