# Generated by Django 4.2.1 on 2023-10-06 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eixo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('instituicao', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('Aluno(a) da Educação Básica', 'Aluno(a) da Educação Básica'), ('Professor(a) da Educação Básica', 'Professor(a) da Educação Básica'), ('Servidor(a) da Educação Básica', 'Servidor(a) da Educação Básica'), ('Aluno(a) da Educação Superior', 'Aluno(a) da Educação Superior'), ('Professor(a) da Educação Superior', 'Professor(a) da Educação Superior'), ('Servidor(a) da Educação Superior', 'Servidor(a) da Educação Superior')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissaoResumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=255)),
                ('coautor1', models.CharField(blank=True, max_length=255)),
                ('coautor2', models.CharField(blank=True, max_length=255)),
                ('coautor3', models.CharField(blank=True, max_length=255)),
                ('coautor4', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('instituicao', models.CharField(max_length=255)),
                ('titulo', models.CharField(max_length=255)),
                ('palavrasChave', models.CharField(max_length=255)),
                ('paper', models.FileField(upload_to='evento/resumos/')),
                ('eixo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evento.eixo')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissaoMinicurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('formacao', models.CharField(choices=[('Graduação', 'Graduação'), ('Especialização', 'Especialização'), ('Mestrado', 'Mestrado'), ('Doutorado', 'Doutorado')], max_length=20)),
                ('instituicao', models.CharField(max_length=255)),
                ('titulo', models.CharField(max_length=255)),
                ('paper', models.FileField(upload_to='evento/minicursos/')),
                ('eixo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evento.eixo')),
            ],
        ),
    ]
