# Generated by Django 4.2.1 on 2023-10-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='categoria',
            field=models.CharField(choices=[('Estudantes da Educação Básica', 'Estudantes da Educação Básica'), ('Estudantes de Graduação', 'Estudantes de Graduação'), ('Estudantes de Pós-Graduação', 'Estudantes de Pós-Graduação'), ('Profissionais da Educação Básica', 'Profissionais da Educação Básica'), ('Profissionais da Educação Superior', 'Profissionais da Educação Superior'), ('Demais Interessados', 'Demais Interessados')], max_length=50),
        ),
    ]
