# Generated by Django 4.2.1 on 2023-11-14 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0002_alter_pessoa_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Minicuro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='InscricaoMinicurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('minicuro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evento.minicuro')),
            ],
        ),
    ]
