# Generated by Django 4.2.1 on 2023-11-14 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0003_minicuro_inscricaominicurso'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Minicuro',
            new_name='Minicurso',
        ),
    ]
