# Generated by Django 4.2.1 on 2023-11-16 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0004_rename_minicuro_minicurso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscricaominicurso',
            old_name='minicuro',
            new_name='minicurso',
        ),
    ]
